name: Clear Announcement File

on:
  schedule:
    # Runs at 00:00 on the 1st day of every month.
    # Adjust cron expression as needed. e.g., '0 0 */21 * *' for every 3 weeks.
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  clear_file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Clear anuncio.txt
        run: |
          echo "" > anuncio.txt

      - name: Commit and push if changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Clear announcement file"
          branch: main # Or your default branch
          file_pattern: anuncio.txt
          commit_user_name: GitHub Action
          commit_user_email: action@github.com
          commit_author: GitHub Action <action@github.com>
